export const fallbackQuotes = {
  motivational: [
    { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    { text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs" },
    { text: "Life is what happens to you while you're busy making other plans.", author: "John Lennon" },
    { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
    { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    { text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
    { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
    { text: "The only impossible journey is the one you never begin.", author: "Tony Robbins" },
    { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
  ],
  funny: [
    { text: "I'm not lazy, I'm on energy saving mode.", author: "Anonymous" },
    { text: "I told my wife she was drawing her eyebrows too high. She looked surprised.", author: "Anonymous" },
    { text: "Why don't scientists trust atoms? Because they make up everything.", author: "Anonymous" },
    { text: "I haven't slept for ten days, because that would be too long.", author: "Mitch Hedberg" },
    { text: "I used to hate facial hair, but then it grew on me.", author: "Anonymous" },
    { text: "I'm reading a book about anti-gravity. It's impossible to put down.", author: "Anonymous" },
    { text: "I told my cat a joke about dogs, but he didn't find it a-mew-sing.", author: "Anonymous" },
    { text: "Why don't eggs tell jokes? They'd crack each other up.", author: "Anonymous" },
    { text: "I'm on a seafood diet. I see food and I eat it.", author: "Anonymous" },
    { text: "Time flies like an arrow. Fruit flies like a banana.", author: "Groucho Marx" },
  ],
};
